export const USER_REQUEST_IF_NEEDED = "USER_REQUEST_IF_NEEDED";
export const USER_FETCH = "USER_FETCH";
export const USERS_FETCH_SUCCESS = "FETCH_FETCH_SUCCESS";
export const USERS_FETCH_FAILED = "FETCH_FETCH_FAILED";
